#!/usr/bin/env bash
# Configures a new Ubuntu machine

sudo apt -y update
sudo apt -y install nginx
#ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i 's/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/github\.com\/Anashm24 permanent;/' /etc/nginx/sites-enabled/default
sudo service nginx restart
