#!/usr/bin/env bash

#remive the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# Configuration of nginx server to listen on port 80 for all active ipv4 ips
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
