#!/usr/bin/env bash
# Display the content of the current directory in a list format, showing only the part of the name after the first dash

for file in *; do
    # Check if the file is not a hidden file
    if [ "${file:0:1}" != "." ]; then
        name_file=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_file"
    fi
done
